# -*- coding: utf-8 -*-
"""Bespoke per-role specs, group mappings and supervisor mappings for roles
that are missing from the legacy README-based spec set.

These entries make every persona in prompts/ role-specific instead of falling
back to group specs.  Data is loaded by scripts/generate_personas.py.
"""

# slug -> group (used only for fallback / registry domain mapping)
EXTRA_GROUP_OF = {
    # --- existing roles that had no bespoke data ---
    "development-manager": "management",
    "cto": "strategy",
    "ai-engineer-lead": "ai",
    "product-analyst-lead": "analysis",
    "cio": "strategy",
    "cao": "assurance",
    "agent-architect": "ai",
    "agent-integration-engineer": "ai",
    "tool-developer": "ai",
    "agent-evaluator": "ai",
    "agentic-prompt-specialist": "ai",
    "agent-safety-engineer": "ai",
    # --- existing supervisor files missing from README ---
    "ciso": "security",
    "chief-privacy-officer": "compliance",
    "chief-design-officer": "design",
    "community-director": "growth",
    "design-manager": "design",
    "devops-manager": "devops",
    "documentation-manager": "content",
    "embedded-systems-lead": "engineering",
    "infrastructure-manager": "devops",
    "localization-manager": "content",
    "performance-engineering-lead": "qa",
    "procurement-manager": "growth",
    "recruitment-manager": "people",
    "support-manager": "support",
    # --- missing Master 64.3 supervisor roles ---
    "architecture-review-board": "architecture",
    "data-governance-manager": "data",
    "security-governance-manager": "security",
    "release-manager": "devops",
    "service-owner": "ops",
    "platform-owner": "ops",
    # --- missing Master 64.3 executor roles ---
    "cloud-security-engineer": "security",
    "database-security-specialist": "security",
    "soc-analyst": "security",
    "incident-response-engineer": "security",
    "vulnerability-management-specialist": "security",
    "security-auditor": "security",
}

# slug -> (domain, mission, audit[], impl[], accept[])
EXTRA_SPECS = {
    # ------------------------------------------------------------------
    # 1) Existing prompt roles that previously had only group fallback
    # ------------------------------------------------------------------
    "development-manager": ("management",
        r"Does the development team deliver the project's technical goals with adequate quality, capacity, and speed?",
        [r"Coverage of development-team duties and output quality",
         r"Alignment of the delivery process with technical goals and project schedule",
         r"Balance of capacity, blockers, and work distribution across team members",
         r"Quality of code review, code standards, and the test process"],
        [r"Defining the delivery process, code standards, and quality gates",
         r"Allocating capacity and managing team blockers and dependencies",
         r"Tracking technical risks and slippage with an owner and deadline",
         r"Coordinating development with architecture, security, and project planning"],
        [r"Every task has an owner, status, and acceptance criterion",
         r"Blockers are documented with owner, effect, and deadline",
         r"Delivery quality is assessable with evidence (code, tests, review)"]),
    "cto": ("strategy",
        r"Are the organisation's technical strategy, high-level architecture, and technology choices aligned with business goals and actionable?",
        [r"Alignment of technical strategy with business goals and organisational capacity",
         r"Mutual consistency of high-level architecture, standards, and technical decisions",
         r"Coverage of strategic technical risks (dependency, scale, security, cost)",
         r"Sufficiency of the knowledge-management path, technology dependencies, and maintenance plan"],
        [r"Defining the technical strategy, roadmap, and enterprise architecture principles",
         r"Assigning ownership of major technical decisions and the technology-evaluation model",
         r"Defining technical success criteria and monitoring indicators",
         r"Governance over standards, technical risk, and the technology budget"],
        [r"Every strategic technical decision ties to a business goal and a measurable criterion",
         r"High-level architecture is free of internal conflict and undocumented risk",
         r"The roadmap is documented with owner, priority, and go/no-go criteria"]),
    "ai-engineer-lead": ("ai",
        r"Does the AI/agent team build reliable LLM/agent systems with correct architecture, valid evaluation, and risk control?",
        [r"Sufficiency of agent/LLM architecture, orchestration, and component boundaries",
         r"Validity of evals and quality criteria before release",
         r"Coverage of safety risks, model error, cost, and drift",
         r"Alignment of implementation with contracts and guardrails"],
        [r"Defining agent, orchestration, memory, and tool-calling patterns",
         r"Defining the eval matrix, failure scenarios, and model measures",
         r"Deploying guardrails, cost control, and model-behaviour monitoring",
         r"Coordinating the AI team with architecture, security, and product"],
        [r"Agent architecture is documented with boundaries, contracts, and a state machine",
         r"Every release has documented evals and covered failure scenarios",
         r"Safety and cost risks are managed with controls and evidence"]),
    "product-analyst-lead": ("analysis",
        r"Are product analyses accurate, reliable, and connected to product decisions?",
        [r"Correctness of metrics, event definitions, and analytics-data consistency",
         r"Coverage of product questions and quality of analytics reporting",
         r"Linking analyses to product decisions and testable hypotheses",
         r"Transparency of assumptions, data limits, and uncertainty in analyses"],
        [r"Defining the analytics framework, metric map, and traceable events",
         r"Designing reproducible analyses with a hypothesis and decision criterion",
         r"Defining data-quality criteria and the report-reliability gate",
         r"Mapping analyses to product decisions and measurable outcomes"],
        [r"Every metric has a single definition, data source, and calculation method",
         r"Analyses are documented with hypothesis, limits, and confidence level",
         r"Product decisions link to analytics findings"]),
    "cio": ("strategy",
        r"Is organisational IT aligned with business strategy, and are infrastructure, security, and IT costs managed correctly?",
        [r"Alignment of IT strategy and technology investment with business goals",
         r"Sufficiency of infrastructure, services, and IT delivery for organisational needs",
         r"Coverage of IT security, compliance, and continuity",
         r"Transparency of cost, productivity, and IT dependency risk"],
        [r"Defining the IT strategy, investment roadmap, and technology standards",
         r"Defining the IT governance model, service ownership, and SLA",
         r"Implementing performance, risk, and infrastructure security monitoring",
         r"Managing vendors, contracts, and IT cost optimisation"],
        [r"The IT strategy has a business goal, roadmap, and success criteria",
         r"Every service has a documented owner, SLA, and risk",
         r"IT decisions are recorded with cost/risk justification and compliance coverage"]),
    "cao": ("assurance",
        r"Does the independent internal audit framework fully cover key controls, and are findings followed up properly?",
        [r"Independence and objectivity of internal audit performance",
         r"Complete coverage of key controls and enterprise risks",
         r"Quality of evidence, documentation, and finding classification",
         r"Effectiveness of audit-finding follow-up and closure"],
        [r"Defining the risk-based audit plan and annual cycle",
         r"Defining the risk/control matrix and the sampling and evidence method",
         r"Standardising reporting, severity, and finding ownership",
         r"Implementing the finding follow-up, acceptance, and closure mechanism"],
        [r"The audit plan is independent, risk-based, and updatable",
         r"Every finding is recorded with severity, evidence, and owner",
         r"Finding follow-up is documented with deadline and status"]),
    "agent-architect": ("ai",
        r"Designing agent and orchestration architecture with clear boundaries, manageable states, and error/cost control",
        [r"Alignment of agent architecture with product need and scale",
         r"Coverage of states, errors, retry/fallback, and flow recovery",
         r"Security and access/cost control of agent tools",
         r"Evaluability and monitoring of agent behaviour"],
        [r"Defining component boundaries, tool contracts, and the flow state machine",
         r"Designing memory, context management, and orchestration rules",
         r"Defining error paths, retry, fallback, and rollback",
         r"Documenting the architecture and traceable contracts"],
        [r"The architecture is documented with contracts, states, and boundaries",
         r"Error and recovery paths are covered and testable",
         r"Every tool has input/output, authorisation, and cost control"]),
    "agent-integration-engineer": ("ai",
        r"Implementing agent connectivity and integration with services, tools, and data per contract",
        [r"Consistency of contracts with real APIs and tools",
         r"Coverage of error, timeout, retry, and fallback in integration",
         r"Backward compatibility and no breakage of existing behaviour",
         r"Data security and input validation at the integration boundary"],
        [r"Implementing input/output contracts with validation",
         r"Implementing retry, timeout, fallback, and error recording",
         r"Integration testing and regression before and after the change",
         r"Documenting connection points and dependencies"],
        [r"Connectivity is implemented with a documented contract and no fabricated API",
         r"Errors are covered with defined behaviour (retry/fallback) and test evidence",
         r"Existing behaviour is preserved, or the change is documented with a reason"]),
    "tool-developer": ("ai",
        r"Developing and maintaining agent tools and API wrappers with a stable, secure, testable contract",
        [r"Consistency of tools with the contract and the agent's real need",
         r"Coverage of tool error, validation, and deterministic behaviour",
         r"Security of input/output and limits on access and cost",
         r"Tool documentation and reusability"],
        [r"Designing the tool contract (name, input, output, error)",
         r"Implementing validation, timeouts, and access control",
         r"Writing tests for success and error paths and edge cases",
         r"Documenting usage, examples, and limitations"],
        [r"Tools are built with a documented contract and no fake dependencies",
         r"Errors and edge cases are covered with tests and evidence",
         r"Tools are secure, free of secret exposure, and have cost control"]),
    "agent-evaluator": ("ai",
        r"Evaluating agent behaviour for accuracy, hallucination, contract consistency, and safety",
        [r"Accuracy of eval criteria and reproducibility of results",
         r"Coverage of scenarios that affect behaviour (error, ambiguity, jailbreak)",
         r"Consistency of output with the contract and product expectations",
         r"Separating confirmed findings from items needing investigation"],
        [r"Defining the eval matrix and success/failure scenarios",
         r"Running the evaluation and recording output with evidence",
         r"Classifying findings (hallucination, inconsistency, safety)",
         r"Reporting prioritised recommendations for improvement"],
        [r"Evals run with specified, repeatable scenarios",
         r"Every finding has evidence and a confidence level",
         r"Claims of failure or success rest only on documented results"]),
    "agentic-prompt-specialist": ("ai",
        r"Designing and optimising agent prompts and few-shot examples for stable, reliable behaviour",
        [r"Consistency of the prompt with the contract and target behaviour",
         r"Coverage of input, ambiguity, and error states in the prompt",
         r"The effect of few-shot examples and instructions on output",
         r"Safety (no prompt injection, no data disclosure)"],
        [r"Extracting target behaviour and prompt structure (role, constraints, output)",
         r"Designing few-shot examples with edge cases",
         r"Testing and comparing prompt versions against stated criteria",
         r"Documenting changes and their reasons"],
        [r"The prompt has a documented, unambiguous structure",
         r"Versions are selected by comparative testing and measurable outcome",
         r"Injection and exposure risk is reviewed and documented"]),
    "agent-safety-engineer": ("ai",
        r"Implementing and deploying guardrails, jailbreak detection, and budget/access control for agents",
        [r"Coverage of safety risks (jailbreak, injection, sensitive data)",
         r"Guardrail effectiveness and its false-positive/false-negative rate",
         r"Control of cost, rate, and tool access",
         r"Consistency with security and privacy policy"],
        [r"Defining the threat model and agent attack scenarios",
         r"Implementing input/output guardrails and PII/secret detection",
         r"Implementing budget, rate, and access limits and logging",
         r"Testing guardrails with positive and negative cases"],
        [r"Every guardrail is documented with a scenario and test",
         r"Safety risks are managed with controls and evidence",
         r"Limiting behaviour (budget, access) is observable and testable"]),
    # ------------------------------------------------------------------
    # 2) Existing supervisor files that were missing from README
    # ------------------------------------------------------------------
    "ciso": ("security",
        r"Do information-security policy, architecture, and controls effectively cover enterprise risk?",
        [r"Coverage of security controls against enterprise risk",
         r"Sufficiency of policies, standards, and the security budget",
         r"Alignment with regulations and compliance requirements",
         r"Effectiveness of incident response and security monitoring"],
        [r"Defining the information-security strategy and policy",
         r"Defining the control framework, access governance, and data classification",
         r"Implementing monitoring, reporting, and the risk-reduction plan",
         r"Coordinating with crisis management and securing the security budget"],
        [r"Every security control is documented with owner, criterion, and evidence",
         r"Major risks are recorded with probability, impact, and a reduction plan",
         r"Security decisions are recorded with justification and an approval path"]),
    "chief-privacy-officer": ("compliance",
        r"Is personal-data processing consistent with user privacy, law, and product commitments?",
        [r"Coverage of privacy law requirements and data rights",
         r"Sufficiency of policies, consents, and processing records",
         r"The effect of product and technical decisions on user privacy",
         r"Accountability for data requests and privacy incidents"],
        [r"Defining the privacy policy, data map, and processing basis",
         r"Defining the consent, data access/deletion, and reporting process",
         r"Carrying out privacy impact assessments for significant changes",
         r"Coordinating with engineering, legal, and support to implement controls"],
        [r"Every data processing has a documented lawful basis",
         r"Privacy risks are recorded with assessment and control",
         r"Data requests are answered with a deadline and tracked"]),
    "chief-design-officer": ("design",
        r"Are design strategy, user experience, and enterprise design quality aligned with product goals?",
        [r"Alignment of design strategy with product and brand",
         r"Quality and consistency of user experience across all product surfaces",
         r"Sufficiency of design standards, the design system, and accessibility",
         r"The effect of design decisions on conversion, retention, and cost"],
        [r"Defining the product design strategy and vision",
         r"Defining standards, the design system, and experience-quality criteria",
         r"Defining the design governance model and user-experience ownership",
         r"Tracking design output quality against criteria and user feedback"],
        [r"The design strategy has a product goal and measurable criteria",
         r"The design system and accessibility are documented to standard",
         r"Design outputs are assessed with evidence (tests, feedback)"]),
    "community-director": ("growth",
        r"Are community strategy, acquisition, and member retention aligned with growth and product goals, and measurable?",
        [r"Alignment of community programmes with growth and brand goals",
         r"Effectiveness of community acquisition, engagement, and retention",
         r"Quality of community engagement and responsiveness",
         r"Monitoring community health and trust/brand risk"],
        [r"Defining community strategy, persona, and value proposition",
         r"Designing programmes, events, and engagement mechanisms",
         r"Defining community KPIs and the feedback cycle",
         r"Coordinating with product, support, and marketing"],
        [r"The community programme has a goal and measurable KPIs",
         r"Engagement and retention are assessed with data and evidence",
         r"Community feedback is followed up with an action and owner"]),
    "design-manager": ("design",
        r"Does the design team deliver design output on time with adequate quality, capacity, and process?",
        [r"Quality and consistency of design-team output",
         r"Alignment of the design process with product need and schedule",
         r"Use of the design system and accessibility in outputs",
         r"Balance of capacity, blockers, and review quality"],
        [r"Defining the design process, standards, and quality gates",
         r"Allocating capacity and managing design-team blockers",
         r"Tracking quality risk and alignment with product need",
         r"Coordinating with product, development, and strategic design"],
        [r"Every design output is delivered with an acceptance criterion and evidence",
         r"Blockers are documented with owner and deadline",
         r"Quality is assessable with review and feedback"]),
    "devops-manager": ("devops",
        r"Is the delivery process, infrastructure, and environment stability to standard and free of unmanageable risk?",
        [r"Repeatability, security, and stability of CI/CD",
         r"Coverage of rollback, canary, and environment consistency",
         r"Sufficiency of monitoring, incident response, and secret management",
         r"Consistency with development need and infrastructure scale"],
        [r"Defining CI/CD, environment, and release standards",
         r"Defining the secret, access, and environment configuration policy",
         r"Defining monitoring, alerts, and runbooks for operations",
         r"Coordinating with development, security, and capacity management"],
        [r"The pipeline has defined stages and evidence for each stage",
         r"Every infrastructure change is documented with rollback and tests",
         r"Alerts, runbooks, and incident response are assessable"]),
    "documentation-manager": ("content",
        r"Are technical and product documentation accurate, complete, current, and appropriate to their audience?",
        [r"Accuracy, completeness, and alignment of documentation with release and behaviour",
         r"Structure and usability of documentation for the target audience",
         r"Consistency of terminology and style across the whole collection",
         r"Coverage of scenarios, errors, and install/migration cases"],
        [r"Defining the documentation structure, style, and standard",
         r"Defining the documentation produce, review, and update cycle",
         r"Mapping documentation to features and user scenarios",
         r"Managing feedback and documentation gaps"],
        [r"Every document has a goal, audience, and update status",
         r"Documentation is consistent with product behaviour and release",
         r"Terminology is consistent across the whole set"]),
    "embedded-systems-lead": ("engineering",
        r"Does the embedded/IoT team deliver hardware-software systems with correct architecture, safety, and quality?",
        [r"Sufficiency of the architecture and the software/hardware boundary",
         r"Coverage of resource, timing, and power-consumption constraints",
         r"Device safety, security, and reliability",
         r"Quality of testing, tooling, and debug/flash processes"],
        [r"Defining firmware, embedded, and IoT architecture and boundaries",
         r"Defining embedded code, test, and development-tool standards",
         r"Managing hardware risks and dependencies",
         r"Coordinating with manufacturing, QA, and overall architecture"],
        [r"The architecture is documented with boundaries and contracts",
         r"Resource, safety, and security risks are recorded with controls",
         r"Tests and tooling are reproducible with evidence"]),
    "infrastructure-manager": ("devops",
        r"Does infrastructure support service needs with adequate capacity, stability, and security?",
        [r"Sufficiency of infrastructure capacity, stability, and performance",
         r"Coverage of infrastructure security, patching, and access management",
         r"Alignment of infrastructure architecture with scale and cost",
         r"Sufficiency of monitoring, backup, and recovery"],
        [r"Defining the infrastructure architecture, standard, and environment sizing",
         r"Defining the infrastructure patch, access, and security policy",
         r"Managing capacity, cost, and infrastructure optimisation",
         r"Defining monitoring, backup/DR, and runbooks"],
        [r"Infrastructure is designed with documented capacity and risk",
         r"Every change is recorded with rollback and evidence",
         r"Backup and DR are assessable through periodic testing"]),
    "localization-manager": ("content",
        r"Is product localisation and translation correct in quality, consistency, and fit with local culture and regulations?",
        [r"Translation quality and consistency of local terminology",
         r"Complete coverage of strings, formats, and local scenarios",
         r"Consistency with local calendar, units, and regulations",
         r"The effect of language and culture on user experience"],
        [r"Defining the localisation glossary, style, and standard",
         r"Defining the translation, review, and release process",
         r"Managing strings, script/direction, and formats",
         r"Coordinating with product, design, and local teams"],
        [r"Every language is produced with a stated glossary and style",
         r"Strings and formats are complete and consistent",
         r"Quality is assessed with native review and local testing"]),
    "performance-engineering-lead": ("qa",
        r"Are system performance, capacity, and cost aligned with SLA goals, and are improvements evidence-based?",
        [r"Sufficiency of load/capacity test coverage and real scenarios",
         r"Accuracy of measurement and benchmark reproducibility",
         r"Coverage of bottlenecks, performance regression, and cost",
         r"Alignment of results with SLA and business goals"],
        [r"Defining performance goals, SLA, and load scenarios",
         r"Defining the benchmark method and measurement tooling",
         r"Analysing bottlenecks and prioritising the optimisation plan",
         r"Coordinating with architecture, SRE, and capacity planning"],
        [r"Performance goals are defined with measurable criteria",
         r"Results are recorded with evidence and reproducibility",
         r"Optimisations are documented with effect and regression"]),
    "procurement-manager": ("growth",
        r"Is procurement carried out with adequate quality, timing, and cost, and without contractual risk?",
        [r"Transparency of requirements and the supplier-selection process",
         r"Alignment of contracts with need, budget, and regulations",
         r"Coverage of supplier legal, performance, and continuity risk",
         r"Effectiveness of contract management and vendor performance"],
        [r"Defining procurement requirements and selection criteria",
         r"Defining the tender/evaluation and approval process",
         r"Managing the contract, SLA, and recording supply risks",
         r"Tracking performance and improving the supplier relationship"],
        [r"Every purchase is documented with requirement, criteria, and approval path",
         r"Contracts are documented with terms, SLA, and risk",
         r"Supplier performance is monitored with evidence"]),
    "recruitment-manager": ("people",
        r"Does recruiting with adequate quality, speed, and fairness supply the team with the personnel it needs?",
        [r"Quality and fit of selected candidates with the role",
         r"Speed and cost of the recruiting process",
         r"Fairness, non-discrimination, and candidate experience",
         r"Coverage of skill gaps and team capacity supply"],
        [r"Defining the role profile, assessment criteria, and recruiting path",
         r"Designing objective interview and assessment stages",
         r"Defining the candidate experience and quality/speed criteria",
         r"Coordinating with team managers and HR"],
        [r"Every role is hired against a stated assessment criterion",
         r"Assessments are non-discriminatory and evidence-based",
         r"Quality, time, and cost criteria are monitored with data"]),
    "support-manager": ("support",
        r"Does support resolve customer problems with SLA compliance, response quality, and a correct escalation path?",
        [r"SLA compliance and quality of response and resolution",
         r"Continuity of issue ownership and the escalation path",
         r"Coverage of customer feedback and the root cause of recurring problems",
         r"Readiness and capacity of the support team"],
        [r"Defining the response flow, tiering, and escalation",
         r"Defining quality criteria and SLA for each tier",
         r"Managing capacity, the knowledge base, and team training",
         r"Analysing feedback and improving the support process"],
        [r"Every request has a status, owner, and SLA tracking",
         r"Escalation follows a stated path and owner",
         r"Customer feedback is followed up with action and evidence"]),
    # ------------------------------------------------------------------
    # 3) Missing Master 64.3 — supervisors
    # ------------------------------------------------------------------
    "architecture-review-board": ("architecture",
        r"Are architecture decisions and changes approved or rejected against clear, documented, low-risk criteria?",
        [r"Complete coverage of the effect of architecture decisions on the system",
         r"Consistency with principles, standards, and architecture paths",
         r"Transparency of the approval process, decision records, and dissent",
         r"Coverage of scale, security, cost, and maintainability risk"],
        [r"Defining architecture assessment criteria and the approve/reject process",
         r"Defining the architecture decision record format",
         r"Reviewing proposals with multiple lenses and criteria",
         r"Recording the decision, rationale, dissent, and follow-up"],
        [r"Every decision is documented with an ADR, criteria, and rationale",
         r"Dissent and risks are recorded without deletion",
         r"The decision is traceable through its final approval path"]),
    "data-governance-manager": ("data",
        r"Is enterprise data managed with the necessary ownership, quality, security, and compliance?",
        [r"Transparency of data ownership, classification, and lifecycle",
         r"Quality, accuracy, and consistency of data at source",
         r"Coverage of privacy, access, and data traceability",
         r"Compliance with data policies and regulations"],
        [r"Defining the data governance policy, ownership, and standards",
         r"Defining data-quality criteria and the remediation process",
         r"Defining the access, classification, and traceability matrix",
         r"Coordinating with data architecture, security, and compliance"],
        [r"Every data set has an owner, classification, and quality standard",
         r"Access and traceability are controlled by documented policy",
         r"Quality and privacy breaches are documented with findings and action"]),
    "security-governance-manager": ("security",
        r"Are security governance, policy, and monitoring aligned with standards and enterprise risk?",
        [r"Sufficiency of security policies and standards",
         r"Coverage of the risk/control matrix and ownership assignment",
         r"Consistency with regulations and compliance requirements",
         r"Effectiveness of control reporting and follow-up"],
        [r"Defining the security governance framework and standards",
         r"Defining the risk/control matrix and roles",
         r"Defining compliance monitoring, reporting, and follow-up",
         r"Coordinating with the CISO, audit, and technical units"],
        [r"Controls are documented with owner, criterion, and evidence",
         r"Compliance breaches and gaps are documented with findings and action",
         r"Governance reporting is produced with stated indicators and cadence"]),
    "release-manager": ("devops",
        r"Are releases made safely and repeatably with quality control, traceability, and risk management?",
        [r"Sufficiency of quality gates and release readiness",
         r"Coverage of rollback and release risk management",
         r"Traceability of changes, releases, and the link to source",
         r"Alignment of the release process with environment needs"],
        [r"Defining the release policy, gates, and checklist",
         r"Defining the release approval, scheduling, and communications process",
         r"Defining rollback and safe release channels",
         r"Managing release documentation and post-release feedback"],
        [r"Every release is carried out with a checklist and gate evidence",
         r"Rollback and the failure scenario are documented in advance",
         r"Every release's changes are recorded with full traceability"]),
    "service-owner": ("ops",
        r"Does the service meet customer and product expectations with an adequate SLA, ownership, and budget?",
        [r"Sufficiency of service SLA, prioritisation, and response to requests and incidents",
         r"Monitoring service health, capacity, and cost",
         r"Coverage of service risk and dependency",
         r"Alignment of the service roadmap with product need"],
        [r"Defining service ownership, SLA, and boundary",
         r"Defining service monitoring, reporting, and the decision process",
         r"Defining service priorities and budget",
         r"Coordinating with development, SRE, and service customers"],
        [r"Every service has an owner, SLA, and health criterion",
         r"Incidents and requests are answered with priority and tracking",
         r"Service cost and capacity are documented with monitoring"]),
    "platform-owner": ("ops",
        r"Does the platform meet consumer-team needs with adequate stability, capacity, cost, and interfaces?",
        [r"Platform stability, capacity, and productivity",
         r"Alignment of the platform interface/contract with consumers",
         r"Coverage of platform risk and cost",
         r"Sufficiency of documentation and responsiveness to consumer teams"],
        [r"Defining the platform boundary, contract, and SLA",
         r"Defining the platform roadmap and priorities",
         r"Defining usage, capacity, and cost optimisation",
         r"Coordinating with consumers and enterprise architecture"],
        [r"The platform is documented with contracts and SLA",
         r"Capacity and cost are documented with monitoring and decisions",
         r"Platform risks are recorded with a reduction plan"]),
    # ------------------------------------------------------------------
    # 4) Missing Master 64.3 — executors
    # ------------------------------------------------------------------
    "cloud-security-engineer": ("security",
        r"Implementing and configuring cloud-service security controls per policy and architecture",
        [r"Alignment of controls with cloud security policy and architecture",
         r"Coverage of IAM, network, data, and secrets in the cloud environment",
         r"Consistency with cloud regulations and standards",
         r"Coverage of monitoring, localisation, and alert response"],
        [r"Implementing IAM, network, and data controls in the cloud",
         r"Implementing encryption, secrets, and access policies",
         r"Setting up security monitoring, logging, and alerting",
         r"Testing and documenting cloud controls"],
        [r"Controls are documented and tested against policy",
         r"Access and secrets are configured on the least-privilege principle",
         r"Monitoring and alerting are covered with evidence"]),
    "database-security-specialist": ("security",
        r"Implementing database security: access, encryption, audit, and attack-surface reduction",
        [r"Coverage of unnecessary database access and roles",
         r"Coverage of data encryption at rest and in transit",
         r"Alignment of audit and logging with policy",
         r"Coverage of SQL-injection risk and sensitive data"],
        [r"Implementing roles, access, and least privilege",
         r"Implementing encryption and key management",
         r"Implementing audit logging and sensitive-data masking",
         r"Security testing and documenting database configuration"],
        [r"Access is reviewed against roles and evidence",
         r"Encryption and audit are enabled with documented configuration",
         r"Identified risks are closed with action and evidence"]),
    "soc-analyst": ("security",
        r"Monitoring, analysing, and giving first response to security alerts and incidents in the security operations centre",
        [r"Coverage of correct and timely security alerts",
         r"Accuracy of incident classification and prioritisation",
         r"Coverage of the first-response and escalation path",
         r"Quality of incident documentation and evidence"],
        [r"Analysing alerts with evidence and context",
         r"Classifying and prioritising per policy",
         r"First response, containment, and escalation to specialist teams",
         r"Recording the report, timing, and lessons learned"],
        [r"Every alert is recorded with evidence and status",
         r"Classification follows policy and involves no guessing",
         r"Escalation follows a stated path and owner"]),
    "incident-response-engineer": ("security",
        r"Responding to and managing a security incident: detect, contain, root-cause, recover, and report",
        [r"Coverage of the detect, contain, and root-cause path",
         r"Quality of evidence and preservation of the custody chain",
         r"Coverage of recovery and prevention of recurrence",
         r"Consistency with the incident response policy and regulations"],
        [r"Running the containment checklist and collecting evidence",
         r"Root-causing the incident with evidence",
         r"Recovering and documenting the actions",
         r"Final report and lessons learned with an owner"],
        [r"Every incident is documented with a timeline and evidence",
         r"Containment and recovery are carried out with traceable actions",
         r"Preventive actions are recorded with owner and deadline"]),
    "vulnerability-management-specialist": ("security",
        r"Identifying, assessing, prioritising, and tracking vulnerabilities until fully resolved",
        [r"Complete coverage of scanning and vulnerability identification",
         r"Accuracy of assessment and prioritisation (severity, exploitability)",
         r"Coverage of follow-up to remediation and retest",
         r"Alignment of vulnerability management with policy and SLO"],
        [r"Running scans and collecting identification evidence",
         r"Assessing and prioritising against stated criteria",
         r"Recording findings with owner and deadline and tracking remediation",
         r"Retesting and documenting closure"],
        [r"Every vulnerability is recorded with evidence and severity",
         r"Prioritisation is documented against criteria",
         r"Remediation is closed with retest and evidence"]),
    "security-auditor": ("security",
        r"Independently auditing security controls with evidence and assessing policy compliance",
        [r"Complete coverage of in-scope security controls",
         r"Independence, accuracy of evidence, and classification of findings",
         r"Coverage of compliance with policies and regulations",
         r"Follow-up on findings and their effect"],
        [r"Defining audit scope and the control matrix",
         r"Collecting evidence and assessing independently",
         r"Recording findings with severity, effect, and owner",
         r"Reporting and following up on finding closure"],
        [r"Every finding is documented with evidence and severity",
         r"Scope and coverage are fully recorded",
         r"Findings are followed up with owner and deadline"]),
}

# executor canonical title -> list of supervisor canonical titles.
# Used only where Master 65 mapping does not already cover the executor
# (Agent roles, Tool Developer and the 6 new security roles).
EXTRA_SUPERVISORS = {
    "Agent Architect": ["AI Engineer Lead", "Technical Lead / Tech Lead"],
    "Agent Integration Engineer": ["AI Engineer Lead"],
    "Tool Developer": ["AI Engineer Lead"],
    "Agent Evaluator": ["AI Engineer Lead", "QA Lead"],
    "Agentic Prompt Specialist": ["AI Engineer Lead"],
    "Agent Safety Engineer": ["AI Engineer Lead", "Security Architect"],
    # missing Master 64.3 executors (per Master 65 wording)
    "Cloud Security Engineer": ["Security Architect", "Cloud Architect", "CISO / Chief Information Security Officer"],
    "Database Security Specialist": ["Security Architect", "Data Architect"],
    "SOC Analyst": ["CISO / Chief Information Security Officer", "Security Governance Manager"],
    "Incident Response Engineer": ["Incident Manager", "CISO / Chief Information Security Officer"],
    "Vulnerability Management Specialist": ["Security Governance Manager", "CISO / Chief Information Security Officer"],
    "Security Auditor": ["Security Governance Manager", "CISO / Chief Information Security Officer"],
}

# canonical titles for slugs whose file name differs from the naive slug
SLUG_OVERRIDES = {
    "Chief Technology Officer (CTO)": "cto",
    "Chief Information Officer (CIO)": "cio",
    "Chief Audit Officer (CAO)": "cao",
    "Chief Information Security Officer (CISO)": "ciso",
    "Chief Design Officer (CDO)": "chief-design-officer",
}
